# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07109261333101b51c10b43596f2140b86267a5684ed13464041c0ffe193588f3f3b85c24cc4a9cc55013763ba00ecf197f5fcaf99ffabc71abfc9b8228c4714

test:
  secret_key_base: 5cf5e236be3937a9dfc9a2342ca28253511d793b0c3c53143b30af070bbb402588af00e9253867165df0b48c17db26191122100bf9d32d8e4387cd22e5b12b37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
